version: "3"
services:
  sts-be:
    build: stack-trace-solver-be/
    ports:
      - "5000:5000"
    volumes:
      - ./stack-trace-solver-be:/sts-be
  sts-fe:
    build: stack-trace-solver-fe/
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./stack-trace-solver-fe/src:/sts-fe/src
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    privileged: true
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: